# Generated by Django 2.2.7 on 2019-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gostos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'O que gosta de fazer',
                'verbose_name_plural': 'Gostos',
                'ordering': ['gosto'],
            },
        ),
    ]
